---
title: "HDRU dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE,echo=FALSE}
knitr::opts_chunk$set(fig.width=14, fig.height=10, dpi=200)

library(flexdashboard)
library(tidyverse)
library(lubridate)
library(plotly)
library(wesanderson)
library(knitr)
library(kableExtra)
```

Figures {data-icon="fa-list"}
=======================================================

```{r dataImport}
admissionData <- read_csv("data/hdru_admission_raw.csv")
#admissionData<-read_csv("data/hdru_admission_patient_outcome_raw.csv")
  # not all PIDs are unique, e.g. KAA7V0 - can people be admitted, then discharged, then re-admitted from HDRU?
  # which variable captures date of discharge?
dailyData <- read_csv("data/hdru_daily_raw.csv")

# some PIDs in daily data that are not in the admission data
# setdiff(dailyData$pid,admissionData$pid)

# can have multiple admissions of same individual, so need to append admission date to pid
admissionData<-admissionData %>% add_column(admission=1)
dailyData<-dailyData %>% add_column(admission=1)

admissionData$data_date<-ymd(admissionData$data_date)
dailyData$data_date<-ymd(dailyData$data_date)

for(pid in names(table(admissionData$pid)[table(admissionData$pid)>1])){
  admDates<-ymd(admissionData$data_date[admissionData$pid==pid])
  for(d in sort(admDates,decreasing=F)[-1]){
    admissionData$admission[admissionData$pid==pid & ymd(admissionData$data_date)>=d]<-admissionData$admission[admissionData$pid==pid & ymd(admissionData$data_date)>=d]+1
    dailyData$admission[dailyData$pid==pid & ymd(dailyData$data_date)>=d]<-dailyData$admission[dailyData$pid==pid & ymd(dailyData$data_date)>=d]+1
  }
}

admissionData$pid<-toupper(admissionData$pid)
dailyData$pid<-toupper(dailyData$pid)
admissionData<-admissionData %>% add_column(pidAdm=paste(sep="_",admissionData$pid,admissionData$admission))
dailyData$pidAdm<-paste(sep="_",dailyData$pid,dailyData$admission)
 # note: no outcome for first admission of KAA7V0 recorded (last and only instance is 'alive, still in critical care area') 

admissionDataMissing<-dailyData %>%
  filter(!is.element(el=pidAdm,set=admissionData$pidAdm)) %>%
  select(pidAdm,data_date) %>%
  group_by(pidAdm) %>%
  summarise(minDate=min(ymd(data_date)))

admissionData<-as_tibble(plyr::rbind.fill(admissionData,admissionDataMissing))
  

# merge data; needed to calculate duration of organ support; use individual files for tables figures that only focus on admission or daily data
datAdmTmp<-admissionData 
datDailyTmp<-dailyData
colnames(datAdmTmp)<-paste(sep="_","adm",colnames(datAdmTmp)) 
colnames(datDailyTmp)<-paste(sep="_","dly",colnames(datDailyTmp))
datMerged<-full_join(datAdmTmp,datDailyTmp,by=c("adm_pidAdm" = "dly_pidAdm"))

osaDur<-datMerged %>%
  select(adm_pidAdm,adm_adm1,adm_adm2,adm_adm3,adm_adm4,adm_adm5,adm_adm6,adm_adm7,adm_adm99,adm_data_date,dly_osa1,dly_osa2,dly_osa3,dly_osa4,dly_osa5,dly_osa6,dly_osa7,dly_osa8,dly_data_date) %>%
  group_by(adm_pidAdm) %>%
  summarise(adm_adm1=first(adm_adm1),
            adm_adm2=first(adm_adm2),
            adm_adm3=first(adm_adm3),
            adm_adm4=first(adm_adm4),
            adm_adm5=first(adm_adm5),
            adm_adm6=first(adm_adm6),
            adm_adm7=first(adm_adm7),
            adm_adm99=first(adm_adm99),
            adm_data_date=first(adm_data_date),
            osa1Dur=sum(dly_osa1[!is.na(dly_osa1)]),
            osa2Dur=sum(dly_osa2[!is.na(dly_osa2)]),
            osa3Dur=sum(dly_osa3[!is.na(dly_osa3)]),
            osa4Dur=sum(dly_osa4[!is.na(dly_osa4)]),
            osa5Dur=sum(dly_osa5[!is.na(dly_osa5)]),
            osa6Dur=sum(dly_osa6[!is.na(dly_osa6)]),
            osa7Dur=sum(dly_osa7[!is.na(dly_osa7)]),
            osa8Dur=sum(dly_osa8[!is.na(dly_osa8)]),
            dly_first_data=min(ymd(dly_data_date))) # counts days where organ support was recorded

tmp1<-ifelse(!is.na(osaDur$adm_adm1) & osaDur$adm_adm1==1 & (is.na(osaDur$dly_first_data) | (!is.na(osaDur$adm_data_date) & ymd(osaDur$adm_data_date)<ymd(osaDur$dly_first_data))),1,0)
tmp2<-ifelse(!is.na(osaDur$adm_adm2) & osaDur$adm_adm2==1 & (is.na(osaDur$dly_first_data) | (!is.na(osaDur$adm_data_date) & ymd(osaDur$adm_data_date)<ymd(osaDur$dly_first_data))),1,0)
tmp3<-ifelse(!is.na(osaDur$adm_adm3) & osaDur$adm_adm3==1 & (is.na(osaDur$dly_first_data) | (!is.na(osaDur$adm_data_date) & ymd(osaDur$adm_data_date)<ymd(osaDur$dly_first_data))),1,0)
tmp4<-ifelse(!is.na(osaDur$adm_adm4) & osaDur$adm_adm4==1 & (is.na(osaDur$dly_first_data) | (!is.na(osaDur$adm_data_date) & ymd(osaDur$adm_data_date)<ymd(osaDur$dly_first_data))),1,0)
tmp5<-ifelse(!is.na(osaDur$adm_adm5) & osaDur$adm_adm5==1 & (is.na(osaDur$dly_first_data) | (!is.na(osaDur$adm_data_date) & ymd(osaDur$adm_data_date)<ymd(osaDur$dly_first_data))),1,0)
tmp6<-ifelse(!is.na(osaDur$adm_adm6) & osaDur$adm_adm6==1 & (is.na(osaDur$dly_first_data) | (!is.na(osaDur$adm_data_date) & ymd(osaDur$adm_data_date)<ymd(osaDur$dly_first_data))),1,0)
tmp7<-ifelse(!is.na(osaDur$adm_adm7) & osaDur$adm_adm7==1 & (is.na(osaDur$dly_first_data) | (!is.na(osaDur$adm_data_date) & ymd(osaDur$adm_data_date)<ymd(osaDur$dly_first_data))),1,0)
tmp8<-ifelse(!is.na(osaDur$adm_adm99) & osaDur$adm_adm99==1 & (is.na(osaDur$dly_first_data) | (!is.na(osaDur$adm_data_date) & ymd(osaDur$adm_data_date)<ymd(osaDur$dly_first_data))),1,0)

osaDur$osa1Dur<-osaDur$osa1Dur+tmp1
osaDur$osa2Dur<-osaDur$osa2Dur+tmp2
osaDur$osa3Dur<-osaDur$osa3Dur+tmp3
osaDur$osa4Dur<-osaDur$osa4Dur+tmp4
osaDur$osa5Dur<-osaDur$osa5Dur+tmp5
osaDur$osa6Dur<-osaDur$osa6Dur+tmp6
osaDur$osa7Dur<-osaDur$osa7Dur+tmp7
osaDur$osa8Dur<-osaDur$osa8Dur+tmp8

rm(tmp1,tmp2,tmp3,tmp4,tmp5,tmp6,tmp7,tmp8)


admissionData<-left_join(admissionData,osaDur,by=c("pidAdm" = "adm_pidAdm"))
# table(admissionData$adm1,admissionData$osa1Dur) # conflicts: 10 with adm1==1, but osa1Dur==0, 1 with adm1==0 but osa1Dur>0
# table(admissionData$adm2,admissionData$osa2Dur) # conflicts: 4 with adm2==1, but osa2Dur==0, 1 with adm2==0 but osa2Dur>0

admissionData<-admissionData %>% add_column(sexFactor=factor(ifelse(admissionData$sex==0,"Female","Male"),levels=c("Female","Male")))
admissionData<-admissionData %>% add_column(pregFactor=factor(ifelse(admissionData$pregnancy==3,"Not known to be pregnant",ifelse(admissionData$pregnancy==2,"Recently pregnant",ifelse(admissionData$pregnancy==1,"Currently pregnant.",NA))),levels=c("Not known to be pregnant","Recently pregnant","Currently pregnant")))
admissionData<-admissionData %>% add_column(weight=4*admissionData$muac-50)
  # Cattermole et al (2016)
  # some super light people!

# height from ulna length estimation was based on a formula for children - hence why so many tall people!
# admissionData$height<-case_when(
#   admissionData$sexFactor=="Male" ~ (4.605*admissionData$ulnar_l+1.308*admissionData$age+28.003)/100,
#   admissionData$sexFactor=="Female" ~ (4.459*admissionData$ulnar_l+1.315*admissionData$age+31.485)/100
# )
#   # Gauld et al (2004); formula gives result in cm, hence dividing by 100 for meters
#   # very very tall people!!!

ulna2HeightConvTable<-read_csv("../20200716_UlnaHeight/DOI_10.1002_9781118786529.csv") # as per Table 10.3 from https://onlinelibrary.wiley.com/doi/pdf/10.1002/9781118786529.app10

ulna2HeightConvFun<-function(ulna,sex,age,convTab=ulna2HeightConvTable){
  col<-case_when(
    sex=="Male" & age<65 ~ "menBelow65yrs_m",
    sex=="Male" & age>=5 ~ "menAbove65yrs_m",
    sex=="Female" & age<65 ~ "womenBelow65yrs_m",
    sex=="Female" & age>=65 ~ "womenAbove65yrs_m",
  )
  
  f<-list()
  f[["menBelow65yrs_m"]]<-approxfun(x=convTab$ulna_cm,y=convTab$menBelow65yrs_m,method="linear",rule=1)
  f[["menAbove65yrs_m"]]<-approxfun(x=convTab$ulna_cm,y=convTab$menAbove65yrs_m,method="linear",rule=1)
  f[["womenBelow65yrs_m"]]<-approxfun(x=convTab$ulna_cm,y=convTab$womenBelow65yrs_m,method="linear",rule=1)
  f[["womenAbove65yrs_m"]]<-approxfun(x=convTab$ulna_cm,y=convTab$womenAbove65yrs_m,method="linear",rule=1)
  
  res<-ifelse(col=="menBelow65yrs_m",1,0)*f[["menBelow65yrs_m"]](ulna) +
    ifelse(col=="menAbove65yrs_m",1,0)*f[["menAbove65yrs_m"]](ulna) +
    ifelse(col=="womenBelow65yrs_m",1,0)*f[["womenBelow65yrs_m"]](ulna) +
    ifelse(col=="womenAbove65yrs_m",1,0)*f[["womenAbove65yrs_m"]](ulna)
  
  return(res)
}

admissionData<-admissionData %>% add_column(height=ulna2HeightConvFun(ulna=admissionData$ulnar_l,sex=admissionData$sexFactor,age=admissionData$age))
  # still fairly tall people: median height is 1.80m -- ie. half are 1.80m or taller...
  # but better than with previous formula from Gauld et al (2004)

admissionData<-admissionData %>% add_column(bmi=admissionData$weight/(admissionData$height^2))
  # these strike me as exceptionally low; lowest ever recorded BMI is 7.5, yet her we have several below that...
admissionData<-admissionData %>% add_column(bmiFactor=factor(case_when(
  admissionData$bmi<18.5 ~ "<18.5",
  admissionData$bmi>=18.5 & admissionData$bmi<25 ~ "18.5-<25",
  admissionData$bmi>=25 & admissionData$bmi<30 ~ "25-<30",
  admissionData$bmi>=30 & admissionData$bmi<40~ "30-<40",
  admissionData$bmi>=40 ~ "40+"),
  levels=c("<18.5","18.5-<25","25-<30","30-<40","40+")
))

admissionData$depFactor<-factor(case_when(
  admissionData$dependecy==1 ~ "Able to live without assistance in daily activities",
  admissionData$dependecy==2 ~ "Minor assistance with some daily activities",
  admissionData$dependecy==3 ~ "Major assistance with majority of or all daily activities",
  admissionData$dependecy==4 ~ "Total assistance with all daily activities"),
  levels=c("Able to live without assistance in daily activities",
           "Minor assistance with some daily activities",
           "Major assistance with majority of or all daily activities",
           "Total assistance with all daily activities")
)

admissionData$hivFactor<-factor(case_when(
  admissionData$serop==0 ~ "No HIV",
  admissionData$serop==1 & admissionData$art==1 ~ "ART compliant",
  admissionData$serop==1 & admissionData$art==2 ~ "ART non-compliant",
  admissionData$serop==1 & admissionData$art==3 ~ "Not on ART"),
  levels=c("No HIV","ART compliant","ART non-compliant","Not on ART")
)

admissionData$tbFactor<-factor(case_when(
  admissionData$lpp==0 | admissionData$tb==0 ~ "No TB",
  admissionData$tb==1 ~ "TB"),
  levels=c("No TB","TB")
)

admissionData$hypFactor<-factor(case_when(
  admissionData$cpp==0 | admissionData$sh==0 ~ "No severe hypertension",
  admissionData$sh==1 ~ "Severe hypertension"),
  levels=c("No severe hypertension","Hypertension")
)

admissionData$ccfFactor<-factor(case_when(
  admissionData$cpp==0 | admissionData$ccf==0 ~ "No congestive cardiac failure",
  admissionData$ccf==1 ~ "Congestive cardiac failure"),
  levels=c("No congestive cardiac failure","Congestive cardiac failure")
)

admissionData$strokeFactor<-factor(case_when(
  admissionData$npp==0 | admissionData$stroke==0 ~ "No stroke",
  admissionData$stroke==1 ~ "Stroke"),
  levels=c("No stroke","Stroke")
)

admissionData$diabetesFactor<-factor(case_when(
  admissionData$hpp==0 | (admissionData$d_insulin==0 & admissionData$d_tablets==0 & admissionData$d_no_tret)==0 ~ "No diabetes",
  admissionData$d_insulin==1 ~ "On insulin",
  admissionData$d_tablets==1 ~ "On tablets",
  admissionData$d_no_tret==1 ~ "Not on treatment"),
  levels=c("No diabetes","On insulin","On tablets","Not on treatment")
)

admissionData$news2<- # https://en.wikipedia.org/wiki/Early_warning_score#/media/File:National_Early_Warning_Score_chart,_Royal_College_of_Physicians,_version_2.png
  case_when(admissionData$nvrrate<=8 ~ 3,
            admissionData$nvrrate>8 & admissionData$nvrrate<=11 ~ 1,
            admissionData$nvrrate>11 & admissionData$nvrrate<=20 ~ 0,
            admissionData$nvrrate>20 & admissionData$nvrrate<=24 ~ 2,
            admissionData$nvrrate>24 ~ 3) +
  case_when(admissionData$ao2sat<=91 ~ 3,
            admissionData$ao2sat>91 & admissionData$ao2sat<=93 ~ 2,
            admissionData$ao2sat>93 & admissionData$ao2sat<96 ~ 1,
            admissionData$ao2sat>=96 ~ 0) +
  case_when(admissionData$adm1==1 ~ 2,
            admissionData$adm1==0 ~ 0) +
  case_when(admissionData$adtemp<=35 ~ 3,
            admissionData$adtemp>35 & admissionData$adtemp<=36 ~ 1,
            admissionData$adtemp>36 & admissionData$adtemp<=38 ~ 0,
            admissionData$adtemp>38 & admissionData$adtemp<=39 ~ 1,
            admissionData$adtemp>39 ~ 2) +
  case_when(admissionData$bp_sys_low<=90 ~ 3,
            admissionData$bp_sys_low>90 & admissionData$bp_sys_low<=100 ~ 2,
            admissionData$bp_sys_low>100 & admissionData$bp_sys_low<=110 ~ 1,
            admissionData$bp_sys_low>110 & admissionData$bp_sys_low<220 ~ 0,
            admissionData$bp_sys_low>=220 ~ 3) +
  case_when(admissionData$hrate_low<=40 ~ 3,
            admissionData$hrate_low>40 & admissionData$hrate_low<=50 ~ 1,
            admissionData$hrate_low>50 & admissionData$hrate_low<=90 ~ 0,
            admissionData$hrate_low>90 & admissionData$hrate_low<=110 ~ 1,
            admissionData$hrate_low>110 & admissionData$hrate_low<=130 ~ 2,
            admissionData$hrate_low>130 ~ 3) +
  case_when(admissionData$avpu==1 ~ 0,
            admissionData$avpu>1 ~ 3) # also gives 3 points for avpu==7 (other)

admissionData$uva<- # doi 10.1136/bmjgh-2017-000344; no GCS or BCS recorded at admission
  case_when(admissionData$adtemp<36 ~ 2,
            admissionData$adtemp>=36 ~ 0) +
  case_when(admissionData$hrate_low<120 ~ 0,
            admissionData$hrate_low>=120 ~ 1) +
  case_when(admissionData$nvrrate<30 ~ 0,
            admissionData$nvrrate>=30 ~ 1) +
  case_when(admissionData$bp_sys_low<90 ~ 1,
            admissionData$bp_sys_low>=90 ~ 0) +
  case_when(admissionData$ao2sat<92 ~ 2,
            admissionData$ao2sat>=92 ~ 0) +
  case_when(is.na(admissionData$serop) | admissionData$serop==0 ~ 0,
            admissionData$serop==1 ~ 2)

admissionData$pfRatio<-
  case_when(admissionData$abga==2 ~ admissionData$abga2/admissionData$abga6, # need to check with DMSU what units these would be measured in
            admissionData$abga==1 ~ (10^(0.48+0.78*log10(admissionData$ao2sat/(admissionData$ao2req/100))))/7.50062) # doi 10.1097/CCM.0b013e31819cefa9; note log10 in the equation; confirm that FiO2 needs to be a fraction, but SpO2 a percentage -- seems too strange...

admissionData<-admissionData %>% add_column(
  agegrp=case_when(admissionData$age<30 ~ "0-30",
                    admissionData$age>=30 & admissionData$age<40 ~ "30-39",
                    admissionData$age>=40 & admissionData$age<50 ~ "40-49",
                    admissionData$age>=50 & admissionData$age<60 ~ "50-59",
                    admissionData$age>=60 ~ "60+"))

dailyData$outcomeFactor<-factor(case_when(
  dailyData$outcome==0 ~ "Dead",
  dailyData$outcome==1 ~ "Alive, in critical care",
  dailyData$outcome==2 ~ "Alive, discharged",
  dailyData$outcome==3 ~ "Absconded"),
  levels=c("Dead","Alive, in critical care","Alive, discharged","Absconded")
)

dailyData$admissionDate<-ymd(admissionData$data_date[match(dailyData$pidAdm,admissionData$pidAdm)])

datOutcome<-dailyData %>%
  arrange(pidAdm,ymd(data_date)) %>%
  mutate(pidAdm=pidAdm,outcome=ifelse(!is.na(outcome) & outcome!=1,1,0)) %>%
  group_by(pidAdm) %>%
  summarise(outcomeKnown=max(outcome),outcome=last(outcomeFactor),LOS=max(ymd(data_date)-ymd(admissionDate)))
levels(datOutcome$outcome)[levels(datOutcome$outcome)=="Alive, in critical care"]<-"Unknown"

admissionData<-left_join(admissionData,datOutcome,by="pidAdm")
```

```{r weekSelect}
#curWeek<-dmy("27/04/2020","04/05/2020","11/05/2020","18/05/2020","25/05/2020")
curWeek<-dmy("27/04/2020","04/05/2020","11/05/2020","18/05/2020","25/05/2020","01/06/2020","08/06/2020","15/06/2020")
  # weeks to start on Mondays
  # this variable to become a shiny input / selection field
minDay<-min(ymd(curWeek))
maxDay<-max(ymd(curWeek)+6)

admissionDataCurPeriod<-admissionData %>%
  filter(ymd(data_date)>=ymd(minDay) & ymd(data_date)<ymd(maxDay))
```

Row {data-width=350}
-----------------------------------------------------------------------

### Weekly admissions, available outcome data, organ support

```{r}
admissionsWeekly<-admissionData %>%
  mutate(outcomeKnown=ifelse(is.na(outcomeKnown),0,1)) %>%
  group_by(week=cut(ymd(admissionData$data_date),"week",start.on.monday=TRUE),.drop=F) %>%
  summarise(n=sum(!is.na(pidAdm)),nOutcomeKnown=sum(outcomeKnown==1)) %>%
  pivot_longer(cols=-week,names_to="countType",values_to="n")
  # outcome data needs to be taken from the daily data
admissionsWeekly$countType<-factor(admissionsWeekly$countType,levels=c("n","nOutcomeKnown"))

admissionsWeekly %>%
  filter(is.element(el=ymd(week),set=ymd(curWeek))) %>%
  ggplot(mapping=aes(x=week,y=n,fill=countType)) +
  geom_bar(position="dodge",stat="identity") +
  scale_fill_manual(values=wes_palette("Zissou1",n=4,type="discrete")[c(1,4)],name="",labels=c("admitted","outcome recorded")) +
  ylab("Frequency") +
  theme_minimal() +
  theme(legend.position="top",text=element_text(size=28),axis.text.x=element_text(angle = 30, hjust = 1)) +
  xlab("Week") 
```

### Age and sex distribution (for period `r minDay` to `r maxDay`)

```{r}
admissionDataSex <- admissionDataCurPeriod %>%
  select(pidAdm,data_date,agegrp,sexFactor) %>%
  group_by(sexFactor,agegrp) %>%
  dplyr::summarize(nadmn = sum(!is.na(pidAdm))) %>%
  ungroup() %>%
  tidyr::complete(sexFactor,agegrp,fill=list(nadmn=0))

ggplot(admissionDataSex,aes(agegrp,nadmn,fill=sexFactor)) +
  geom_bar(position="stack",stat="identity") +
  xlab("Age at admission") +
  ylab("Frequency") +
  theme_minimal() +
  theme(legend.position="top",text=element_text(size=28)) +
  scale_fill_manual(values = wes_palette("Zissou1",n=4,type="discrete")[c(1,4)],name="")
```


Row {data-width=350}
-----------------------------------------------------------------------
### Organ support

```{r}
admissionsWeekly<-admissionData %>%
  mutate(outcomeKnown=ifelse(is.na(outcomeKnown),0,1)) %>%
  group_by(week=cut(ymd(admissionData$data_date),"week",start.on.monday=TRUE),.drop=F) %>%
  summarise(n=sum(!is.na(pidAdm)),percOrganSupportOxygen=100*sum(adm1==1)/sum(!is.na(pidAdm)),percOrganSupportFluidBalance=100*sum(adm2==1)/sum(!is.na(pidAdm))) %>%
  filter(is.element(el=ymd(week),set=ymd(curWeek)))

admissionsWeeklyLong <-admissionsWeekly %>%
  pivot_longer(cols=c(percOrganSupportOxygen,percOrganSupportFluidBalance),names_to="percType",values_to="percentage")
  # outcome data needs to be taken from the daily data
admissionsWeeklyLong$percType<-factor(admissionsWeeklyLong$percType,levels=c("percOrganSupportOxygen","percOrganSupportFluidBalance"))

admissionsWeekly<-admissionsWeekly %>% mutate(
  maxPerc=pmax(percOrganSupportOxygen,percOrganSupportFluidBalance),
  nLabel=paste(sep="","n = ",n))

ggplot() +
  geom_bar(data=admissionsWeeklyLong,mapping=aes(x=week,y=percentage,fill=percType),position="dodge",stat="identity") +
  scale_fill_manual(values=wes_palette("Zissou1",n=4,type="discrete")[c(1,4)],name="",labels=c("required oxygen support","required fluid balance")) +
  ylab("Percentage") +
  theme_minimal() +
  theme(legend.position="top",text=element_text(size=28),axis.text.x=element_text(angle = 30, hjust = 1)) +
  xlab("Week") +
  geom_text(data=admissionsWeekly,mapping=aes(x=week,y=-4,label=nLabel),colour="grey50",size=8)
```

### Organ support duration

```{r}
admissionData %>%
  filter(ymd(data_date)>=ymd(minDay) & ymd(data_date)<ymd(maxDay)) %>%
  select(pidAdm,osa1Dur,osa2Dur) %>%
  pivot_longer(cols=-pidAdm,names_to="osType",values_to="duration") %>%
  mutate(osType=factor(ifelse(osType=="osa1Dur","Oxygen administration.","Careful fluid balance."),levels=c("Oxygen administration.","Careful fluid balance."))) %>%
  
  ggplot(mapping=aes(x=osType,y=duration,fill=osType)) +
  geom_boxplot() +
  scale_fill_manual(values=wes_palette("Zissou1",n=4,type="discrete")[c(1,4)]) +
  theme_minimal() +
  theme(legend.position="none",text=element_text(size=28)) +
  xlab("Organ support") +
  ylab("Duration")

  # ggplot() +
  # stat_summary(
  #   mapping = aes(x = osType, y = duration, color=osType, lwd=1.75),
  #   fun.min = min,
  #   fun.max = max,
  #   fun = median
  # ) +
  # scale_color_manual(values=wes_palette("Zissou1",n=4,type="discrete")[c(1,4)]) +
  # theme(legend.position="none",text=element_text(size=28)) +
  # xlab("Organ support") +
  # ylab("Duration")
```



Tables {data-icon="fa-list"}
======================================================================


```{r usefulRoutinesForTables}
sumStatFun<-function(dat,var,groupVar=NULL,groups=NULL,values=NULL,breaks=NULL,rightTF=F){
  # dat = data frame
  # var = variable in dat for which the summary statistics are to be computed
  # groupVar = variable to stratify the summary statistics by and to compute comparison p-values for
  # values = levels or values (if variable is categorical or discrete)
  # breaks = breaks to categorise a continuous variable
  # rightTF = logical, indicating if the intervals should be closed on the right (and open on the left) or vice versa
  
  if(is.null(groupVar) | is.null(groups)){
    dat$tmpGroup<-rep("allSamples",nrow(dat))
    groups<-"allSamples"
    groupVar<-"tmpGroup"
  }
  
  dat<-as.data.frame(dat)
  
  # continuous variables
  if(is.null(values) & is.null(breaks)){
    ssFunTmp<-function(dat,var){
      res<-data.frame(
        stat=c("N (%)","mean (SD)","median (IQR)","range"),
        stat1Val=c(sum(!is.na(dat[,var])),mean(dat[,var],na.rm=T),median(dat[,var],na.rm=T),min(dat[,var],na.rm=T)),
        stat2Val=c(sum(!is.na(dat[,var]))/nrow(dat),sd(dat[,var],na.rm=T),quantile(dat[,var],probs=0.25,na.rm=T),max(dat[,var],na.rm=T)),
        stat3Val=c(NA,NA,quantile(dat[,var],probs=0.75,na.rm=T),NA),
        stringsAsFactors=F)
      return(res)
    }
      
    res<-ssFunTmp(dat=dat,var=var)
    colnames(res)<-paste(sep="","overall_",colnames(res))
    
    if(length(groups)>1){
      for(g in groups){
        if(sum(!is.na(dat[dat[,groupVar]==g,var]))>0){
          resTmp<-ssFunTmp(dat=dat[dat[,groupVar]==g,],var=var)
          colnames(resTmp)<-paste(sep="",g,"_",colnames(resTmp))
          res<-cbind(res,resTmp[,-1])
        }else{
          resTmp<-data.frame(stat1Val=rep(NA,4),stat2Val=NA,stat3Val=NA)
          colnames(resTmp)<-paste(sep="",g,"_",colnames(resTmp))
          res<-cbind(res,resTmp)
        }
      }
    }
    
    res$p<-NA
    if(length(groups)==2){
      try(res$p[2]<-t.test(as.formula(paste(sep="~",var,groupVar)),data=dat)$p.value,silent=T)
      try(res$p[3]<-wilcox.test(as.formula(paste(sep="~",var,groupVar)),data=dat)$p.value,silent=T)
    }else if(length(groups)>2){
      try(res$p[2]<-summary(aov(as.formula(paste(sep="~",var,groupVar)),data=dat))[[1]][1,"Pr(>F)"],silent=T)
      try(res$p[3]<-kruskal.test(as.formula(paste(sep="~",var,groupVar)),data=dat)$p.value,silent=T)
    }
  }else{
    # categorical or discrete variables
    if(!is.null(values)){
      tmp<-dat[,var]
      levels(tmp)
    # continuous variables to be categorised
    }else if(!is.null(breaks)){
      tmp<-cut(dat[,var],breaks=breaks,right=rightTF,ordered_result=T)
    }
    nonMissing<-sum(!is.na(dat[,var]))
    for(g in groups){nonMissing<-c(nonMissing,sum(!is.na(dat[,var]) & dat[,groupVar]==g))}
    resCounts<-rbind(nonMissing,cbind(table(tmp),table(tmp,dat[,groupVar])))
    resProps<-resCounts
    for(j in 1:ncol(resProps)){resProps[-1,j]<-resProps[-1,j]/resProps[1,j]}
    resProps[1,1]<-resProps[1,1]/nrow(dat)
    for(j in 1:length(groups)){resProps[1,j+1]<-resProps[1,j+1]/sum(dat[,groupVar]==groups[j])}
    res<-data.frame(statName="N (%)",
                    overall_count=resCounts[,1],
                    overall_prop=resProps[,1],
                    NA,
                    stringsAsFactors=F)
    if(length(groups)>1){
      for(j in 2:ncol(resProps)){
        res<-cbind(res,resCounts[,j],resProps[,j],NA)
        colnames(res)[(ncol(res)-2):(ncol(res)-1)]<-paste(sep="_",colnames(resCounts)[j],c("count","prop"))
      }
    }

    res$p<-NA
    if(length(groups)>1){
      res$p[2]<-fisher.test(resCounts[-1,-1])$p.value
    }
  }
    
  return(res)
}

reformatForTable<-function(sumStatOutput,varDescription,contCat,nsmall=2){
  if(contCat=="continuous"){
    varTmp<-c(paste(sep="",varDescription," [n=",as.integer(sumStatOutput[sumStatOutput[,"overall_stat"]=="N (%)","overall_stat1Val"])," (",format(nsmall=1,round(digits=1,100*sumStatOutput[sumStatOutput[,"overall_stat"]=="N (%)","overall_stat2Val"])),"%)]"),
              "  Mean (SD)",
              "  Median (IQR)"
    )
    stat1Tmp<-c("",
                format(nsmall=nsmall,round(digits=2,sumStatOutput[sumStatOutput[,"overall_stat"]=="mean (SD)","overall_stat1Val"])),
                format(nsmall=nsmall,round(digits=2,sumStatOutput[sumStatOutput[,"overall_stat"]=="median (IQR)","overall_stat1Val"]))                                                                                                                       
    )
    stat2Tmp<-c("",
                paste(sep="","(",format(nsmall=nsmall,round(digits=2,sumStatOutput[sumStatOutput[,"overall_stat"]=="mean (SD)","overall_stat2Val"])),")"),
                paste(sep="","(",paste(collapse=",",format(nsmall=nsmall,round(digits=2,unlist(sumStatOutput[sumStatOutput[,"overall_stat"]=="median (IQR)",c("overall_stat2Val","overall_stat3Val")])))),")")                                                                                                                          
    )
    
  }else if(contCat=="categorical"){
    varTmp<-c(paste(sep="",varDescription," [n=",as.integer(sumStatOutput["nonMissing","overall_count"])," (",format(nsmall=1,round(digits=1,100*sumStatOutput["nonMissing","overall_prop"])),"%)]"),
              paste(sep="","  ",rownames(sumStatOutput)[-1])
    )
    stat1Tmp<-""
    stat2Tmp<-""
    for(lvl in rownames(sumStatOutput)[-1]){
      stat1Tmp<-c(stat1Tmp,
                  sumStatOutput[rownames(sumStatOutput)==lvl,"overall_count"]
                  )
      stat2Tmp<-c(stat2Tmp,
                  paste(sep="","(",format(nsmall=1,round(digits=1,100*sumStatOutput[rownames(sumStatOutput)==lvl,"overall_prop"])),"%)")
      )
    }
  }
  
  res<-data.frame(variable=varTmp,stat1=stat1Tmp,stat2=stat2Tmp)
  return(res)
}
```

Row {data-width=350}
-----------------------------------------------------------------------

```{r table1}
tbl1<-reformatForTable(sumStatOutput=sumStatFun(dat=admissionDataCurPeriod,var="age"),varDescription="Age at admission in years",contCat="continuous")
tbl1<-rbind(tbl1,reformatForTable(sumStatOutput=sumStatFun(dat=admissionDataCurPeriod,var="sexFactor",values=levels(admissionDataCurPeriod$sexFactor)),varDescription="Sex, n (%)",contCat="categorical"))
tbl1<-rbind(tbl1,reformatForTable(sumStatOutput=sumStatFun(dat=admissionDataCurPeriod[admissionDataCurPeriod$sexFactor=="Female",],var="pregFactor",values=levels(admissionDataCurPeriod$pregFactor)),varDescription="Pregnancy status, n (% of females)",contCat="categorical"))
tbl1<-rbind(tbl1,reformatForTable(sumStatOutput=sumStatFun(dat=admissionDataCurPeriod,var="bmiFactor",values=levels(admissionDataCurPeriod$bmiFactor)),varDescription="Body mass index categories, n (%)",contCat="categorical"))

varDescIdx<-grep(tbl1$variable,pattern="\\[n=")
varDescLabels<-tbl1[varDescIdx,1]
tbl1<-tbl1[-varDescIdx,]

kable(tbl1,col.names=NULL,row.names=F,caption=paste(sep="","Patient characteristics: demographics (period ",minDay," to ",maxDay,"; total admissions n=",nrow(admissionDataCurPeriod),")")) %>%
  kable_styling("striped", full_width = F) %>%
  #add_header_above(c("Demographics" = 1, paste(sep="","Patients to HDRU from ",minDay," to ",maxDay,"[n = ",nrow(admissionData),"]") = 2)) %>%
  pack_rows(varDescLabels[1], 1, 2) %>%
  pack_rows(varDescLabels[2], 3, 4) %>%
  pack_rows(varDescLabels[3], 5, 7) %>%
  pack_rows(varDescLabels[4], 8, 12)
```

```{r table2}
tbl2<-reformatForTable(sumStatOutput=sumStatFun(dat=admissionDataCurPeriod,var="depFactor",values=levels(admissionDataCurPeriod$depFactor)),varDescription="Dependency prior to admission, n (%)",contCat="categorical")
tbl2<-rbind(tbl2,reformatForTable(sumStatOutput=sumStatFun(dat=admissionDataCurPeriod,var="hivFactor",values=levels(admissionDataCurPeriod$hivFactor)),varDescription="HIV, n (%)",contCat="categorical"))
tbl2<-rbind(tbl2,reformatForTable(sumStatOutput=sumStatFun(dat=admissionDataCurPeriod,var="tbFactor",values=levels(admissionDataCurPeriod$tbFactor)),varDescription="TB, n (%)",contCat="categorical"))
tbl2<-rbind(tbl2,reformatForTable(sumStatOutput=sumStatFun(dat=admissionDataCurPeriod,var="hypFactor",values=levels(admissionDataCurPeriod$hypFactor)),varDescription="Hyptertension, n (%)",contCat="categorical"))
tbl2<-rbind(tbl2,reformatForTable(sumStatOutput=sumStatFun(dat=admissionDataCurPeriod,var="ccfFactor",values=levels(admissionDataCurPeriod$ccfFactor)),varDescription="Congestive cardiac failure, n (%)",contCat="categorical"))
tbl2<-rbind(tbl2,reformatForTable(sumStatOutput=sumStatFun(dat=admissionDataCurPeriod,var="strokeFactor",values=levels(admissionDataCurPeriod$strokeFactor)),varDescription="Stroke, n (%)",contCat="categorical"))
tbl2<-rbind(tbl2,reformatForTable(sumStatOutput=sumStatFun(dat=admissionDataCurPeriod,var="diabetesFactor",values=levels(admissionDataCurPeriod$diabetesFactor)),varDescription="Diabetes, n (%)",contCat="categorical"))

varDescIdx<-grep(tbl2$variable,pattern="\\[n=")
varDescLabels<-tbl2[varDescIdx,1]
tbl2<-tbl2[-varDescIdx,]

kable(tbl2,col.names=NULL,row.names=F,caption=paste(sep="","Patient characteristics: medical history (period ",minDay," to ",maxDay,"; total admissions n=",nrow(admissionDataCurPeriod),")")) %>%
  kable_styling("striped", full_width = F) %>%
  #add_header_above(c("Demographics" = 1, paste(sep="","Patients to HDRU from ",minDay," to ",maxDay,"[n = ",nrow(admissionData),"]") = 2)) %>%
  pack_rows(varDescLabels[1], 1, 4) %>%
  pack_rows(varDescLabels[2], 5, 8) %>%
  pack_rows(varDescLabels[3], 9, 10) %>%
  pack_rows(varDescLabels[4], 11, 12) %>%
  pack_rows(varDescLabels[5], 13, 14) %>%
  pack_rows(varDescLabels[6], 15, 16) %>%
  pack_rows(varDescLabels[7], 17, 20)
```

```{r table3}
tbl3<-reformatForTable(nsmall=0,sumStatOutput=sumStatFun(dat=admissionDataCurPeriod,var="news2"),varDescription="NEWS2 score",contCat="continuous")[c(1,3),]
tbl3<-rbind(tbl3,reformatForTable(nsmall=0,sumStatOutput=sumStatFun(dat=admissionDataCurPeriod,var="uva"),varDescription="UVA score",contCat="continuous")[c(1,3),])
tbl3<-rbind(tbl3,reformatForTable(nsmall=0,sumStatOutput=sumStatFun(dat=admissionDataCurPeriod,var="pfRatio"),varDescription="PF ratio",contCat="continuous"))
tbl3<-rbind(tbl3,reformatForTable(nsmall=0,sumStatOutput=sumStatFun(dat=admissionDataCurPeriod,var="pfRatio",breaks=c(0,13.3,26.7,Inf)),varDescription="PF ratio",contCat="categorical"))

tbl3$stat2<-gsub(pattern="\\( ",replacement="\\(",tbl3$stat2)

varDescIdx<-grep(tbl3$variable,pattern="\\[n=")
varDescLabels<-tbl3[varDescIdx,1]
tbl3<-tbl3[-varDescIdx,]

kable(tbl3,col.names=NULL,row.names=F,caption=paste(sep="","Patient characteristics: acute severity (period ",minDay," to ",maxDay,"; total admissions n=",nrow(admissionDataCurPeriod),")")) %>%
  kable_styling("striped", full_width = F) %>%
  #add_header_above(c("Demographics" = 1, paste(sep="","Patients to HDRU from ",minDay," to ",maxDay,"[n = ",nrow(admissionData),"]") = 2)) %>%
  pack_rows(varDescLabels[1], 1, 1) %>%
  pack_rows(varDescLabels[2], 2, 2) %>%
  pack_rows(varDescLabels[3], 3, 7)
```

```{r table4}
admissionDataCurPeriod$outcome<-factor(case_when(
  admissionDataCurPeriod$outcome=="Dead"~"Died",
  admissionDataCurPeriod$outcome=="Alive, discharged"~"Discharged",
  admissionDataCurPeriod$outcome=="Absconded"~"Absconded",
  admissionDataCurPeriod$outcome=="Unknown"~"Unknown"),
  levels=c("Discharged","Died","Absconded","Unknown"))

admissionDataCurPeriod<-admissionDataCurPeriod %>%
  add_column(
    adm1Factor=factor(ifelse(admissionDataCurPeriod$adm1==1,"Oxygen","No oxygen"),levels=c("Oxygen","No oxygen")),
    adm2Factor=factor(ifelse(admissionDataCurPeriod$adm2==1,"Fluid balance","No fluid balance"),levels=c("Fluid balance","No fluid balance")),
    adm3Factor=factor(ifelse(admissionDataCurPeriod$adm3==1,"Neurological observation","No neurological observation"),levels=c("Neurological observation","No neurological observation")),
    adm4Factor=factor(ifelse(admissionDataCurPeriod$adm4==1,"Intravenous drug (not vasoactive)","No intravenous drug (not vasoactive)"),levels=c("Intravenous drug (not vasoactive)","No intravenous drug (not vasoactive)")),
    adm5Factor=factor(ifelse(admissionDataCurPeriod$adm5==1,"Intravenous drug (vasoactive)","No intravenous drug (vasoactive)"),levels=c("Intravenous drug (vasoactive)","No intravenous drug (vasoactive)")),
    adm6Factor=factor(ifelse(admissionDataCurPeriod$adm6==1,"Continuous monitoring","No continuous monitoring"),levels=c("Continuous monitoring","No continuous monitoring")),
    adm7Factor=factor(ifelse(admissionDataCurPeriod$adm7==1,"Intubation & ventilation","No intubation & ventilation"),levels=c("Intubation & ventilation","No intubation & ventilation")),
    adm99Factor=factor(ifelse(admissionDataCurPeriod$adm99==1,"Other","No other"),levels=c("Other","No other"))
  )

tbl4<-reformatForTable(sumStatOutput=sumStatFun(dat=admissionDataCurPeriod,var="outcome",values=levels(admissionDataCurPeriod$outcome)),varDescription="Outcome at the end of critical care, n (%)",contCat="categorical")
tbl4<-rbind(tbl4,reformatForTable(nsmall=0,sumStatOutput=sumStatFun(dat=admissionDataCurPeriod,var="LOS"),varDescription="Length of stay",contCat="continuous")[c(1,3),])
tbl4<-rbind(tbl4,reformatForTable(nsmall=0,sumStatOutput=sumStatFun(dat=admissionDataCurPeriod[admissionDataCurPeriod$outcome=="Discharged",],var="LOS"),varDescription="Length of stay (critical care survivors)",contCat="continuous")[c(1,3),])
tbl4<-rbind(tbl4,reformatForTable(nsmall=0,sumStatOutput=sumStatFun(dat=admissionDataCurPeriod[admissionDataCurPeriod$outcome=="Died",],var="LOS"),varDescription="Length of stay (critical care non-survivors)",contCat="continuous")[c(1,3),])
tbl4<-rbind(tbl4,reformatForTable(sumStatOutput=sumStatFun(dat=admissionDataCurPeriod,var="adm1Factor",values=levels(admissionDataCurPeriod$adm1Factor)),varDescription="Organ support, n (%)",contCat="categorical")[1:2,])
tbl4<-rbind(tbl4,reformatForTable(sumStatOutput=sumStatFun(dat=admissionDataCurPeriod,var="adm2Factor",values=levels(admissionDataCurPeriod$adm2Factor)),varDescription="Organ support, n (%)",contCat="categorical")[1:2,])
tbl4<-rbind(tbl4,reformatForTable(sumStatOutput=sumStatFun(dat=admissionDataCurPeriod,var="adm3Factor",values=levels(admissionDataCurPeriod$adm3Factor)),varDescription="Organ support, n (%)",contCat="categorical")[1:2,])
tbl4<-rbind(tbl4,reformatForTable(sumStatOutput=sumStatFun(dat=admissionDataCurPeriod,var="adm4Factor",values=levels(admissionDataCurPeriod$adm4Factor)),varDescription="Organ support, n (%)",contCat="categorical")[1:2,])
tbl4<-rbind(tbl4,reformatForTable(sumStatOutput=sumStatFun(dat=admissionDataCurPeriod,var="adm5Factor",values=levels(admissionDataCurPeriod$adm5Factor)),varDescription="Organ support, n (%)",contCat="categorical")[1:2,])
tbl4<-rbind(tbl4,reformatForTable(sumStatOutput=sumStatFun(dat=admissionDataCurPeriod,var="adm6Factor",values=levels(admissionDataCurPeriod$adm6Factor)),varDescription="Organ support, n (%)",contCat="categorical")[1:2,])
tbl4<-rbind(tbl4,reformatForTable(sumStatOutput=sumStatFun(dat=admissionDataCurPeriod,var="adm7Factor",values=levels(admissionDataCurPeriod$adm7Factor)),varDescription="Organ support, n (%)",contCat="categorical")[1:2,])
tbl4<-rbind(tbl4,reformatForTable(sumStatOutput=sumStatFun(dat=admissionDataCurPeriod,var="adm99Factor",values=levels(admissionDataCurPeriod$adm99Factor)),varDescription="Organ support, n (%)",contCat="categorical")[1:2,])


varDescIdx<-grep(tbl4$variable,pattern="\\[n=")
varDescLabels<-tbl4[varDescIdx,1]
tbl4<-tbl4[-varDescIdx,]

kable(tbl4,col.names=NULL,row.names=F,caption=paste(sep="","Patient outcomes (period ",minDay," to ",maxDay,"; total admissions n=",nrow(admissionDataCurPeriod),")")) %>%
  kable_styling("striped", full_width = F) %>%
  #add_header_above(c("Demographics" = 1, paste(sep="","Patients to HDRU from ",minDay," to ",maxDay,"[n = ",nrow(admissionData),"]") = 2)) %>%
  pack_rows(varDescLabels[1], 1, 4) %>%
  pack_rows(varDescLabels[2], 5, 5) %>%
  pack_rows(varDescLabels[3], 6, 6) %>%
  pack_rows(varDescLabels[4], 7, 7) %>%
  pack_rows(varDescLabels[5], 8, 15)
```